import jsPDF from 'jspdf';
import { CertificateDetails, SecurityScoreData } from '../types';

export const generatePDF = (
  domain: string, 
  certData: CertificateDetails, 
  scoreData: SecurityScoreData,
  explanation: string
) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFillColor(15, 23, 42); // Slate 900
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.text("HTTPS Security Report", 20, 20);
  doc.setFontSize(12);
  doc.setTextColor(148, 163, 184);
  doc.text(`Target: ${domain} | Generated by CertVis Pro`, 20, 30);

  // Score Section
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(16);
  doc.text("Security Assessment", 20, 60);
  
  doc.setFontSize(40);
  doc.setTextColor(scoreData.color);
  doc.text(`${scoreData.score}/100`, 20, 80);
  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.text(`Grade: ${scoreData.grade}`, 80, 75);
  
  let y = 95;
  scoreData.breakdown.forEach(item => {
      doc.setTextColor(item.passed ? '#10b981' : '#ef4444');
      doc.setFontSize(10);
      doc.text(item.passed ? "PASS" : "FAIL", 20, y);
      doc.setTextColor(0,0,0);
      doc.text(item.label, 40, y);
      y += 8;
  });

  // Certificate Details
  y += 15;
  doc.setFontSize(16);
  doc.text("Certificate Details", 20, y);
  y += 10;
  
  doc.setFontSize(11);
  const details = [
      ["Common Name", certData.commonName],
      ["Issuer", certData.issuer],
      ["Valid From", new Date(certData.validFrom).toLocaleDateString()],
      ["Valid To", new Date(certData.validTo).toLocaleDateString()],
      ["Algorithm", certData.algorithm],
      ["Key Size", certData.keySize],
      ["Signature", certData.signatureAlgorithm],
  ];

  details.forEach(([key, value]) => {
      doc.setFont("helvetica", "bold");
      doc.text(`${key}:`, 20, y);
      doc.setFont("helvetica", "normal");
      doc.text(String(value), 60, y);
      y += 8;
  });

  // Explanation
  y += 15;
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Analysis Summary", 20, y);
  y += 10;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  
  const splitText = doc.splitTextToSize(explanation, 170);
  doc.text(splitText, 20, y);

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text("Generated automatically by CertVis Pro. Not a legal security audit.", 105, 280, { align: "center" });

  doc.save(`${domain}-security-report.pdf`);
};